version: '2.1'
services:
  node:
    image: node:9.3.0
    entrypoint:
      - node_modules/.bin/nodemon
    command:
      - server.js
    working_dir: /code/development
    volumes:
      - ../:/code
    links:
      - php-fpm
    depends_on:
      - php-fpm
  php-fpm:
    image: php:7.1.10-fpm
    working_dir: /code/development
    volumes:
      - ../:/code
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./config/php-fpm.conf:/usr/local/etc/php-fpm.conf
    entrypoint:
      - php-fpm
    command: []
  prometheus:
    image: prom/prometheus:v1.7.1
    command:
      - --config.file
      - /etc/prometheus/prometheus.yml
      - --log.level
      - warn
      - --log.format
      - logger:stdout?json=true
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - node
    depends_on:
      - node

