version: '2.1'
networks:
  grpc-router:
    external:
      name: grpcrouter_grpc-router
services:
  node:
    image: node:9.3.0
    entrypoint:
      - node_modules/.bin/nodemon
    command:
      - server.js
    working_dir: /code
    env_file:
      - .env
    volumes:
      - ./:/code
    networks:
      - grpc-router
    links:
      - php-fpm
    depends_on:
      - php-fpm
  php-fpm:
    image: php:7.1.10-fpm
    volumes:
      # - ./:/var/www/html
      - ./:/code
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./config/php-fpm.conf:/usr/local/etc/php-fpm.conf
    entrypoint:
      - php-fpm
    command: []
    env_file:
      - .env
    networks:
      - grpc-router
